version: '3'

services:
  fastapi:
    build: .
    env_file:
      - .env.prod
    command: sh -c "gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000 --workers 2"
    ports:
      - "8000:8000"
    restart: always
